name: build nepaliconv

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3 # Checkout the repository content to github runner.

      - name: build # Run the run.py to get the latest data
        run: make nepaliconv
